
[环境]
	#无注释
	下雨时的迷雾 = true
	#在中洲维度显示新的雨、雪、沙尘暴、效果
	新的天气渲染 = true
	#无注释
	迷雾山脉的迷雾 = true
	#极光/北方的光芒
	极光 = true
	#无注释
	日光炫目 = true
	#启用/禁用中洲维度的天空渲染
	模组天空 = true
	#替换中洲维度的雨水粒子效果
	新的雨水粒子 = true
	#启用/禁用中洲维度的云层渲染
	模组的云 = true
	#无注释
	#范围: > 0
	云层范围 = 1024

[图形界面]
	#进入游戏时显示魔戒模组自定义的主界面
	模组主界面 = true
	#无注释
	褐色地图 = false
	#一旦显示过一遍后会自动设为false
	显示世界类型提示 = true
	#无注释
	地图文字 = true

[显示]
	#屏幕上的指南针是否显示坐标和生物群系
	指南针信息 = true
	#修改结盟条在屏幕上的y轴坐标。负值向上，正值向下。
	#范围: > -2147483648
	结盟条y坐标 = 0
	#在中洲维度显示屏幕上的指南针
	指南针 = true
	#修改结盟条在屏幕上的x轴坐标。负值向左，正值向右。
	#范围: > -2147483648
	结盟条x坐标 = 0
	#在非魔戒模组的维度仍然显示结盟条
	到处显示结盟条 = false

[模型]
	#天鹅骑士的胸甲背上的翅膀对数
	#范围: 0 ~ 24
	多阿姆洛斯胸甲羽翼对数 = 12

[音效]
	#无注释
	风声 = true
	#无注释
	新雷声 = true
	#无注释
	新雨声 = true

